version: "{build}"
shallow_clone: true

branches:
  only:
  - master

image: Visual Studio 2019
configuration: Release
platform: Any CPU

environment:
  configuration: $(configuration)

init:
- cmd: msbuild /version /nologo
- cmd: dotnet --version

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\NCode.QuerySpecifications.*.nupkg'
  name: Packages

deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: oqVKOGZD+OkIgQQyAdd/hJcagdEY6yQA6lWfH2nINI+GmRcABF6vtslzmQxDqU62